// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/justin/echome-be/config"
	"github.com/justin/echome-be/internal/app"
	character2 "github.com/justin/echome-be/internal/domain/character"
	"github.com/justin/echome-be/internal/domain/conversation"
	"github.com/justin/echome-be/internal/handler"
	"github.com/justin/echome-be/internal/infra"
	"github.com/justin/echome-be/internal/infra/aliyun"
	"github.com/justin/echome-be/internal/infra/character"
	"github.com/justin/echome-be/internal/infra/db"
	"github.com/justin/echome-be/internal/infra/mimo"
	"github.com/justin/echome-be/internal/infra/storage"
)

import (
	_ "github.com/justin/echome-be/docs"
)

// Injectors from wire.go:

// InitializeApplication creates a new Application with all dependencies
// 参数: configPath - 配置文件路径
func InitializeApplication(configPath2 string) (*app.Application, error) {
	configConfig, err := config.Load(configPath2)
	if err != nil {
		return nil, err
	}
	databaseConfig := config.GetDatabaseConfig(configConfig)
	dbDB, err := db.NewDB(databaseConfig)
	if err != nil {
		return nil, err
	}
	query := db.NewQuery(dbDB)
	characterRepository := character.NewCharacterRepository(query)
	aliClient := aliyun.ProvideAliClient(configConfig)
	client := mimo.ProvideMimoClient(configConfig)
	asrProvider, err := infra.ProvideASRProvider(configConfig, aliClient, client)
	if err != nil {
		return nil, err
	}
	llmProvider, err := infra.ProvideLLMProvider(configConfig, aliClient, client)
	if err != nil {
		return nil, err
	}
	repo := infra.ProvideAIRepo(aliClient, asrProvider, llmProvider)
	characterService := character2.NewCharacterService(characterRepository, repo)
	ttsProvider, err := infra.ProvideTTSProvider(configConfig, aliClient, client)
	if err != nil {
		return nil, err
	}
	conversationService := conversation.NewConversationService(repo, ttsProvider, characterService)
	objectStorage, err := storage.ProvideObjectStorage(configConfig)
	if err != nil {
		return nil, err
	}
	int64_2 := config.GetMaxUploadSize(configConfig)
	handlers := handler.NewHandlers(characterService, repo, conversationService, objectStorage, int64_2)
	application := app.NewApplication(configConfig, handlers, objectStorage)
	return application, nil
}
